### ISSUE TITLE
Nette v3 support

### ISSUE THREAD

**Issue by solcik** [contributte/event-dispatcher#16]
```Service latte.latteFactory: Nette\DI\Definitions\FactoryDefinition::addSetup() is deprecated, use ->getResultDefinition()->addSetup()```

What is the plan in regards of versions of this package against Nette v2 vs v3? This package does not have a dependency on nette/di, so this change would break it for nette v2.

**Comment by mabar** [comment]
We plan to release v1.0 for all packages. With 1.0 will be dropped support for nette < 3.0.

**Comment by solcik** [comment]
Please let me know if I can be of any help. I would be glad to push contributte packages towards nette v3 support. I am migrating a big project to Nette3 and from Kdyby to Contributte.

**Comment by JakubBarta** [comment]
Hi guys,
what's the situation? Do you need help with v1.0?
