### ISSUE TITLE
Outdated doc - dispatch() arguments order

### ISSUE THREAD

**Issue by ghost** [contributte/event-dispatcher#19]
Hi, 
event dispatching examples are outdated and no longer works. 

[Changed in Symfony 4.3](https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching).

Thanks for this project!

**Comment by mabar** [comment]
It still works, it's just soft-deprecated. But thanks anyway. Closed by https://github.com/contributte/event-dispatcher/commit/3fe87d5567862ca08645cc3515bd2fa6cf23fb33
