### ISSUE TITLE
Use EventName::class or EventName::NAME instead of Something::XYZ_EVENT

### ISSUE THREAD

**Issue by JanMikes** [contributte/event-dispatcher#2]
As described in [symplify/symplify#168](https://github.com/Symplify/Symplify/issues/168#issue-229044878) it is much better to work with in IDE as you can cmd(ctrl)+click to class and directly see what event is passed and what methods does it have.

**Comment by f3l1x** [comment]
Solved via https://github.com/contributte/event-application-bridge/blob/master/.docs/README.md#bridge-wrench.

Thanks for reporting.
