### ISSUE TITLE
Nette bridges

### ISSUE THREAD

**Issue by enumag** [contributte/event-dispatcher#3]
The [documentation](https://github.com/contributte/event-dispatcher/tree/master/.docs#bridges-recycle) says something about event-application-bridge and event-security-bridge. However the repository for the second one is [empty](https://github.com/contributte/event-security-bridge).

Can you fix the documentation? It is confusing.

**Comment by f3l1x** [comment]
@enumag Thanks for the notice.

I have better idea, I fill that empty repo with my prepared code. :-) Stay tuned.

**Comment by f3l1x** [comment]
Btw, does it make sense to split to these bridges to you?

**Comment by enumag** [comment]
It does. Although it's not entirely necessary in my opinion. Depends on your preference.
