### ISSUE TITLE
Tracy debugger

### ISSUE THREAD

**Issue by bartko-s** [contributte/event-dispatcher#36]
Ahoj @f3l1x Programujem extension ktora loguje eventy do Tracy. Ak by som to integroval priamo do tohto repa. Dostalo by sa to do stabilnej verzie alebo by som to programoval zbytocne? Teraz to mam vo vlastnom repe https://github.com/bartko-s/nette-event-logger je to este len beta verzia ale funguje.

**Comment by f3l1x** [comment]
Ahoj, mrkni na https://github.com/contributte/event-dispatcher/pull/22, uz nejake nastrely byly. Rad bych to tam jednou dostal.

**Comment by bartko-s** [comment]
Ahoj @f3l1x do vlastneho repa som dorobil jednoduchy event logger.
Loguje to dispatchnute eventy a obvolanych listenerov. Ak event implementuje funkciu __toString tak v logu je aj viac info o evente.
Logger zatial funguje len ak je lazy nastavene na true.
Skus si to otestovat. A napis mi ci to ma sancu dostat do stable verzie.

https://github.com/bartko-s/event-dispatcher/tree/tracy-logger
